export const PHYSICS_BOMB =
  'Ok, not actually a bomb. I just wanted to make it more interesting rather than a single dot moving around. It is simply a bunch of random blobs with random target destination. More specifically, given a random destination, each blob will start from the middle of the screen and reach the target using direction vector. However, this is not enough because you would end up with a blob reaching destination in light speed! To make it seem "smooth" I used dissipation factor to specify how fast it plays out and then I use linear interpolation to slow down the movement of the blob as it closes in to the destination.';

export const WEB_SCRAPERS = "I have quite a few web-scrapers. It is quite nice to have scripts that do all the data gathering for you, it is also really REALLY practical and I use it often. What is a web-scraper? It is a program that goes onto the internet without actually opening the browser and automatically download data in all sorts of format in batch. Most obvious usages is for machine learning, you could scraper lots of images to train an image AI, texts for language AI, etc. The hardest part of web-scraping is knowing how to scrape dynamic websites because unlike static websites where everything is already given, you need to make extra requests or you need to know specifically what headers you need in your request. Furthermore, due to the amount of data you are able to scrape, you can easily exceed 10GB, this means a good file structure is REALLY nice to have. I made my web-scrapers able to fetch/update existing websites.";

export const UNIVERSITY_THESIS = "For my university, I created an educational application for the Medical University of Warsaw. The application is meant for professors to manage groups and assign tasks to students. Students on the other hand will be able to receive the tasks to work on. Many features were implemented, I have, in accordance to the medical professor's suggestions, made functionalities that will assist professors to know more about the students better in the form of statistics. Of course, I have made sure there are permission restrictions to ensure there is no room for unwanted curiosities."

export const PERSONAL_PROJECTS =
  "Physics simulation, Webscraper, Raspi server, Automated video editing, File organizer, Video stream downloader ...";
export const SNOWFLAKE_ENGINEER =
  "Frontend development in ReactTS, Hackathon, Public deployment, Teamwork, Communication, Working with multiple departments";
export const UNIVERSITY_TEXT =
  "I learned Java, C++ and C# and later self-taught myself Python, Javascript/Typescript, React";

export const WHAT_CAN_I_DO_FOR_YOU_1 = `First and foremost, I have graduated from Polish-Japanese Academy of Information Technology, I hold an engineer's degree with the highest grade possible. I would like to assume that I have put in the efforts to stand out from most if not all my peers because I constantly engaged myself in activities/materials outside of the university curriculum, thereby making me more versatile. I say this mainly because I have noticed that 9/10 self-taught engineers are better than most CS students I come across, so I'm copying them :P. A degree weighs really precious little :/.
`;
export const WHAT_CAN_I_DO_FOR_YOU_2 = `As my engineering thesis, I have created a web application (frontend, backend, database, deployment on azure) so I am quite familiar with web related apps, SaaS, business logics, etc. I have created web-scrapers which has taught me a lot about HTTP, TCP and UDP requests, more than I was taught in university, which gave me a more low level understanding than endpoints to endpoints understanding in most REST applications. And file structure, yikes, it is not hard but it can get harder when you have so much data. I learn many programming languages, currently Rust, this lets me understand code from different spectrums and allows me to be more critical towards each programming language I come across. Java pls no. I had plans to create more physics simulations as they sound challenging and it sounds cool on a resume but I have recently decided to start creating a game, something which I have never done, good lucks to me.`;

export const WHAT_CAN_I_DO_FOR_YOU_3 = `All in all, I am a great learner, I hope. I have been to a big corpo and I know how things work in companies. The first step to get to know the codebase is quite important to get up to speed with colleagues. And thank goodness I am not afraid of asking questions in companies (I was asking around for horror stories in my previous company, heard some scary ones).`;
